server:
  port: 0

spring:
  application:
    name: member
  datasource:
    url: jdbc:mysql://trendflow.site:3306/member?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: trendflow
    password: trendflow205.!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate: info

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}}

greeting:
  message: Welcome